destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/qumulo-doc"
port: 4010
output: pdf
#product: Qumulo Administrator Guide
print_title: Qumulo Administrator Guide
#print_subtitle: version 6.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: administrator_guide_sidebar
